POST http://localhost:3002/api/user/create
Content-Type: application/json

{
    "username": "aser.456",
    "email": "user5@gmail.com",
    "name": "lê văn mạnh",
    "password": "1234567",
    "rePassword": "1234567"
}
//eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOTkxOGJmMTY0MGFiM2M5ZWU2YzdkYyIsImlhdCI6MTYzNzQyMzI5NSwiZXhwIjoxNjQwMDE1Mjk1fQ.-hZ0YF56x1IfIIQj38Hovr1obfrzchZ8qi8l-ZyqOeY

###
POST http://localhost:3002/api/user/login
Content-Type: application/json

{
    "account": "user3",
    "password": "1234567"
}

###
POST http://localhost:3002/api/user/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOWVlNjJlZTYwZGM0ZGE0MjA0NDQwNSIsImlhdCI6MTYzOTYyNTA5MCwiZXhwIjoxNjQyMjE3MDkwfQ.NFoWCjovGhM4JwvW9wvc6gUIrQhTvvwHQuplruNG2s4
Content-Type: application/json

{
    "filter": "",
    "search": ""
}

###

POST http://localhost:3002/user/update/61991809deaacfab2f7df47b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOWExMzViMTc3MjZlMjQ0YzI0MDQ2OCIsImlhdCI6MTYzNzQ4NzQ3NCwiZXhwIjoxNjQwMDc5NDc0fQ.zK3AhzboTaqCsV2nE2H3N-0NxRhH01-WP5ksR5SbPOo

{
   "username": "user2"
}

###
GET http://localhost:3002/api/category/list

###
GET http://localhost:3002/api/category/get/thoi-sudvfd

###
POST http://localhost:3002/api/category/create 
Content-Type: application/json

{
    "name": "Công nghệ"
}

###
POST http://localhost:3002/api/post/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYWUxNDFkYzhmMTAxYzQ0ZWIwOTk0YiIsImlhdCI6MTYzODc5ODM2NSwiZXhwIjoxNjQxMzkwMzY1fQ.FD3W7RXA6J_Ah-n1Xf28fv-kZOZgDDzV7jalE_o7yIs

{
    "title": "Đây là bài viết số 2 này",
    "category": "61ae1a80234d0294332d4127",
    "content": "Nội dung cho bài 2 này"
    
}

###
post http://localhost:3002/api/post/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYWUxNDFkYzhmMTAxYzQ0ZWIwOTk0YiIsImlhdCI6MTYzODc5ODM2NSwiZXhwIjoxNjQxMzkwMzY1fQ.FD3W7RXA6J_Ah-n1Xf28fv-kZOZgDDzV7jalE_o7yIs

###
post http://localhost:3002/api/user/update/61b0d2d7c205973ad1a77036
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYWUxNDFkYzhmMTAxYzQ0ZWIwOTk0YiIsImlhdCI6MTYzODc5ODM2NSwiZXhwIjoxNjQxMzkwMzY1fQ.FD3W7RXA6J_Ah-n1Xf28fv-kZOZgDDzV7jalE_o7yIs

{
    "username": "kdfnvkjdf"
}

###
GET http://localhost:3002/api/post/get/ha-noi-lien-tuc-mo-rong-dia-ban-dung-hoat-dong-khong-thiet-yeu-1640080378815.html
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYWUxNDFkYzhmMTAxYzQ0ZWIwOTk0YiIsImlhdCI6MTYzODc5ODM2NSwiZXhwIjoxNjQxMzkwMzY1fQ.FD3W7RXA6J_Ah-n1Xf28fv-kZOZgDDzV7jalE_o7yIs

###
GET http://localhost:3002/api/role/list

###
POST http://localhost:3002/api/comment/create
Content-Type: application/json

{
    "post": "61c1d3f954fe5f2033ffa622",
    "author": "61a658945afef3ee5c570c6c",
    "name": "ánkjadvs"
}

###
GET http://localhost:3002/api/dashboard/get